### ISSUE TITLE
Question: node-pre-gyp-github

### ISSUE THREAD

**Issue by CliffS** [AlCalzone/node-aead-crypto#1]
Does [node-pre-gyp-github](https://www.npmjs.com/package/node-pre-gyp-github) need to be a full dependency?  It would save about 1.7MB if if could be moved to dev-dependency.

**Comment by AlCalzone** [comment]
Yes, it does. It tries to download precompiled binaries from github during installation of the library, so it has to be a full dependency.
At least it was like this the last time i checked

**Comment by CliffS** [comment]
Fair enough.  Just seemed a bit OTT. :)
