### ISSUE TITLE
Cannot find module 'node-pre-gyp' (ARM)

### ISSUE THREAD

**Issue by neophob** [AlCalzone/node-aead-crypto#7]
Added tradfri client to our project, now it fails with this issue.

```
 Error: Cannot find module 'node-pre-gyp'
     at Function.Module._resolveFilename (module.js:538:15)
     at Function.Module._load (module.js:468:25)
     at Module.require (module.js:587:17)
     at require (internal/module.js:11:18)
     at Object.<anonymous> (/opt/node_modules/node-aead-crypto/index.js:1:76)
     at Module._compile (module.js:643:30)
     at Object.Module._extensions..js (module.js:654:10)
     at Module.load (module.js:556:32)
     at tryModuleLoad (module.js:499:12)
     at Function.Module._load (module.js:491:3)
     at Module.require (module.js:587:17)
     at require (internal/module.js:11:18)
     at Object.<anonymous> (/opt/node_modules/node-dtls-client/build/TLS/AEADCipher.js:20:26)
```
using node 8 on armv7l, try to see if I can find out why.

I use `node-aead-crypto v1.1.3`

**Comment by neophob** [comment]
looks like a similar issue was resolved with #4 

looks like use the downloaded image:

```
00:13:22.641 > node-aead-crypto@1.1.0 install /node_modules/node-aead-crypto
00:13:22.641 > node lib/install.js
00:13:22.641 
00:13:25.111 running default installation script
00:13:32.554 
00:13:32.554 > node-aead-crypto@1.1.0 install:default /node_modules/node-aead-crypto
00:13:32.555 > node-pre-gyp install --fallback-to-build
00:13:32.555 
00:13:42.903 [node-aead-crypto] Success: "/node_modules/node-aead-crypto/build/Release/node-v57-linux-arm/node_aead_crypto.node" is installed via remote
00
```

**Comment by AlCalzone** [comment]
I'm currently having problems with `node-pre-gyp` which this package is using to download precompiled binaries. But that only affects Windows.

Do you have a full npm installation log from the initial installation? Seems like `node-pre-gyp` is not being installed. Or you could try version 1.1.3.

**Comment by neophob** [comment]
I use version 1.1.3. wild guess: is node-pre-gyp not included because of the `bundledDependencies` setting in package.json? 

When I download the binary package there's only the binary file included but not node-pre-gyp - i *assume* this should be in when I read the doc about `bundledDependencies` (you might be lucky and another project depends node-pre-gyp, then of course it would work). in in the index file (`/node-aead-crypto/index.js`) we require node-pre-gyp explicit: `var binary = require('node-pre-gyp');`

**Comment by AlCalzone** [comment]
> I use version 1.1.3. wild guess: is node-pre-gyp not included because of the bundledDependencies setting in package.json?

Actually it should be included in the tarball for the npm package `node-aead-crypto` because of that setting. When I manually download the tarball using `npm pack node-aead-crypto` I can see it in `node_modules`.
I verified just some hours ago trying to track down another error. On my windows machine, `npm i node-aead-crypto` fails to download the precompiled binary but continues to build it.

I think you are looking at the package from github, which should be downloaded by `node-pre-gyp` and only includes the binary. Please check your installation log to see if there is some error popping up during installation.

Requiring the package works for me:
```
PS C:\Users\domin\Documents\Visual Studio 2017\Repositories\node-dtls-client> node
> require("node-aead-crypto")
{ ccm: { encrypt: [Function], decrypt: [Function] },
  gcm: { encrypt: [Function], decrypt: [Function] } }
>
(To exit, press ^C again or type .exit)
>
```

**Comment by neophob** [comment]
thanks @AlCalzone you're right. `npm pack node-aead-crypto` does in fact add the required node_modules.

But looking at my final asset - the node-pre-gyp is missing

**Comment by neophob** [comment]
Ok definitive a bug on my side. I do run a npm prune script that removes all obsolete files from node modules (like build_log.txt or *.md) - of course i removed node-gyp there too, thats why it fails.

this is the first package is see that uses node-gyp as runtime dependency, is it possible to change that?

**Comment by AlCalzone** [comment]
> is it possible to change that?

First of all: `node-pre-gyp != node-gyp`. 
As that module does several things, its not possible to remove it from the dependencies, see also https://github.com/mapbox/node-pre-gyp:

> Without this your module will not be safely installable for downstream applications that have a depedency on node-pre-gyp in the npm tree (without bundling npm deduping might break the install when node-pre-gyp is moved in flight)

It is used to:
* locate already installed binaries (as their path will vary depending on the platform you're on)
* download precompiled binaries for your platform, which severely speeds up the installation on slow machines
* start the compilation process on platforms that are not in my precompilation matrix.

As I wrote in #8, all this hassle would go away if there's some way to use 8 byte auth tags natively in NodeJS. Last time i checked it was not possible, but things may have changed.

**Comment by neophob** [comment]
Thanks for clarify and your time! i'll close this
