### ISSUE TITLE
Obsolete when nodejs supports 

### ISSUE THREAD

**Issue by neophob** [AlCalzone/node-aead-crypto#8]
ran a quick `crypto.getCiphers()` on node vv6.9.1 and v8.9.4:

```
  'aes-128-ccm',
  'aes-128-gcm',
  'aes-192-ccm',
  'aes-192-gcm',
  'aes-256-ccm',
  'aes-256-gcm',
  'id-aes128-CCM',
  'id-aes128-GCM',
  'id-aes192-CCM',
  'id-aes192-GCM',
  'id-aes256-CCM',
  'id-aes256-GCM',
```

does this module include additional ciphers?

**Comment by AlCalzone** [comment]
Let me check. If that's the case it would make things hell of a lot easier... When I built the DTLS client, not all necessary ciphers were supported.

**Comment by AlCalzone** [comment]
I think the problem are the different auth tag lengths. There are versions with a 16 byte auth tag (`aes-xxx-ccm`) and an 8 byte auth tag (`aes-xxx-ccm8`) which are both necessary for full spec support. The default NodeJS methods have no way to specify the auth tag length.

**Comment by AlCalzone** [comment]
https://medium.com/the-node-js-collection/the-node-js-project-introduces-latest-release-line-node-js-10-x-bf07abfa9076

Seems that NodeJS 10 may make this obsolete 😀 
https://github.com/nodejs/node/commit/1e07acd476309e7ddc4981160b89731b61a31179

**Comment by neophob** [comment]
ole! another reason to use node 10 ;)

**Comment by AlCalzone** [comment]
https://github.com/AlCalzone/node-dtls-client v0.5.3 no longer uses this library on NodeJS 10+
https://github.com/AlCalzone/node-dtls-client#053-2018-05-01

**Comment by neophob** [comment]
damn you are fast!
